-- lua/plugins/core/telescope.lua
return {}
-- return {
--   "nvim-telescope/telescope.nvim",
--   tag = "0.1.5",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     {
--       "nvim-telescope/telescope-fzf-native.nvim",
--       build = "make",
--     },
--   },
--   keys = {
--     { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find files" },
--     { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Live grep" },
--     { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
--     { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Help tags" },
--   },
--   config = function()
--     require("telescope").setup({
--       defaults = {
--         -- Catppuccinと相性の良い設定
--         borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
--         -- 透過設定
--         -- winblend = 0,  -- 0で完全に透明
--         -- layout_config = {
--         --   width = 0.8,
--         --   height = 0.8,
--       },
--       extensions = {
--         fzf = {
--           fuzzy = true,                    -- false will only do exact matching
--           override_generic_sorter = true,  -- override the generic sorter
--           override_file_sorter = true,     -- override the file sorter
--           case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
--           -- the default case_mode is "smart_case"
--         }
--       }
--     })
--     require("telescope").load_extension("fzf")
--   end,
-- }
